---
# Clone Oh My ZSH & change user shell to zsh

- name: Cloning oh-my-zsh
  become: false
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  register: cloning
  tags: [git_pull]

- name: Creating new ~/.zshrc
  become: false
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  when: cloning
  tags: [default_zshrc]
