language: python

python:
  - '3.5'

before_script:
  - pip install -r requirements.txt
  - mv tests/.travis_ansible.cfg ansible.cfg
  - mv tests/files/testing_key_rsa.pub tests/files/id_rsa.pub
  - mv tests/files .

script:
  - ansible --version
  - ansible-lint -v ./*/*.yml -x 404,401,301
  - ansible-playbook tests/test.yml --connection=local --become --force-handlers
  - ansible-playbook tests/test.yml --connection=local --become --force-handlers
    # | grep -q 'changed=0.*failed=0'
    # && (echo 'Idempotence test: pass' && exit 0)
    # || (echo 'Idempotence test: fail' && exit 1)

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/

# Ref: 
# * https://devhints.io/travis
# * https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github