---
# Fresh Pi
# Designed to take a fresh pi after Etcher to getting docker installed
# -------------------------------------

- name: Set Local Info, Hostname, User Information, and Expand Filesystem
  hosts: "{{ target_host | default('new_pi') }}"
  remote_user: pi
  become: true
  roles:
    - role: mrreyes512.fresh_raspi
      raspi_config_update_packages: yes
      raspi_config_expanded_filesystem: yes
      raspi_config_memory_split_gpu: 16
      raspi_config_ensure_optimal_cpu_params: yes
      raspi_config_locale: en_US.UTF-8
      raspi_config_timezone: America/Chicago
      raspi_config_hostname: "{{ inventory_hostname }}"
      raspi_config_enable_camera: no
      raspi_config_fail_on_auth_test: yes
      raspi_config_replace_user:
        name: mreyes
        path_to_ssh_key: "~/.ssh/id_rsa.pub"
      raspi_config_reboot_max_wait_time: 300
      raspi_config_required_packages:
        - vim
        - zsh
        - git
