---
############################################
# This will:
# * Set my new password
# * Copy my SSH keys for authorized_keys
# * Copy my ~/aliases
# * Add source my aliases to ~/.bashrc
# * Copy my vimrc && vim_colors
# * Clone Vundle
############################################

# --------------------------------
# Copy SSH keys to remote ~/.ssh/authorized_keys if exist
- name: Send SSH keys to authorized_keys
  authorized_key:
    user: "{{ ansible_ssh_user }}"
    state: present
    key: "{{ item }}"
  with_file:
    - "{{ playbook_dir }}/../files/id_rsa.pub"

# --------------------------------
# Set up my aliases
- name: Send (my).aliases file
  copy:
    src: "{{ playbook_dir }}/../files/aliases"
    dest: ~/.aliases

- name: Add source to ~/.aliases in ~/.bashrc
  lineinfile:
    path: ~/.bashrc
    insertafter: EOF
    line: "[[ -f ~/.aliases ]] && source ~/.aliases"
    backup: yes

# --------------------------------
# Install MY_PACKAGES
- name: Sudo Install My Packages
  apt:
    pkg: "{{ MY_PACKAGES }}"
    # pkg: "{{ item }}"
    state: present
    update_cache: "{{ UPDATE_CACHE }}"
  # with_items: "{{ MY_PACKAGES }}"
  become: true
  when: '"y" in sudo_attempt'

# Does VIM exist?
- name: Is VIM installed?
  command: vim --version
  ignore_errors: yes
  notify: send_vim_config

# Does ZSH exist?
- name: Is ZSH installed?
  command: zsh --version
  ignore_errors: yes
  notify: send_zsh_config
