# ZSHRC config
# Author: Mark Reyes; mrreyes512@gmail.com

# -------------------------------------------------------------------
# Oh My ZSH Config
# -------------------------------------------------------------------
# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="powerlevel9k/powerlevel9k"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# HIST_STAMPS="mm/dd/yyyy"
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"
export HISTTIMEFORMAT="%Y-%m-%d %T "


# -------------------------------------------------------------------
# ZSH Plugins
# -------------------------------------------------------------------
plugins=(
	git
	git-flow
	brew
	zsh-autosuggestions
	osx
	docker
	vagrant
	python
	zsh-syntax-highlighting
	)


# -------------------------------------------------------------------
# System Sources and Path config
# -------------------------------------------------------------------
# PATH
export PATH="/Volumes/Home/mrreyes512/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/ec2/ec2-api-tools-1.7.5.1/bin:/Applications/Postgres.app/Contents/Versions/latest/bin"
export HOMEBREW_GITHUB_API_TOKEN="2a1a842f207f67dcac6fbc34bdaab43d40c26b1b"
# export MANPATH="/usr/local/man:$MANPATH"

# Sources
source $ZSH/oh-my-zsh.sh
[[ -e ~/.aliases ]] && source ~/.aliases
[[ -e ~/.zsh.custom ]] && source ~/.zsh.custom
[[ -e ~/bin/tmuxinator.zsh ]] && source ~/bin/tmuxinator.zsh
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
compctl -g '~/.itermocil/*(:t:r)' itermocil

# added by travis gem
[ -f /Volumes/home/mrreyes512/.travis/travis.sh ] && source /Volumes/home/mrreyes512/.travis/travis.sh
export PATH="/usr/local/opt/apr/bin:$PATH"
export PATH="/usr/local/opt/apr-util/bin:$PATH"
export PATH="/usr/local/opt/php@7.0/bin:$PATH"
export PATH="/usr/local/opt/php@7.0/sbin:$PATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8


# -------------------------------------------------------------------
# ZSH Syantax Highlight
# -------------------------------------------------------------------
# https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/pattern.md
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)
# To have commands starting with `rm -rf` in red:
ZSH_HIGHLIGHT_PATTERNS+=('rm -rf *' 'fg=white,bold,bg=red')
ZSH_HIGHLIGHT_PATTERNS+=('rmf *' 'fg=white,bold,bg=red')
# Declare the variable
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=red,bold'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=green'
ZSH_HIGHLIGHT_STYLES[alias]='fg=cyan'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=magenta,bold'
ZSH_HIGHLIGHT_STYLES[path]=none
#ZSH_HIGHLIGHT_STYLES[globbing]=none
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=blue'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=blue,bold'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=blue,bold'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]=none
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=yellow,bold'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=red'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=yellow,bold'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=red'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[assign]='fg=yellow'


# -------------------------------------------------------------------
# ZSH Powerline config
# -------------------------------------------------------------------
# https://github.com/bhilburn/powerlevel9k
# Powerlevel Prompt options
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="\n\e[1D"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%n ❯ "

MY_BACK='238'; MY_FORE='white'
POWERLEVEL9K_TIME_FOREGROUND='white'
POWERLEVEL9K_TIME_BACKGROUND='025'
POWERLEVEL9K_DIR_HOME_FOREGROUND='white'
POWERLEVEL9K_DIR_HOME_BACKGROUND='238'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='white'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='238'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='white'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='238'

POWERLEVEL9K_CUSTOM_HOSTNAME="echo $(hostname -s)"
POWERLEVEL9K_CUSTOM_HOSTNAME_BACKGROUND="238"
POWERLEVEL9K_CUSTOM_HOSTNAME_FOREGROUND="yellow"

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator time virtualenv dir )
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( vcs custom_hostname )


# -------------------------------------------------------------------
# ZSHRC Final Settings
# -------------------------------------------------------------------

# Display hostname and external IP address if connecting via SSH
if [[ -n $SSH_CONNECTION ]]; then
		# Settings when ssh'd into a box

		# Print hostname
		figlet $(hostname) 2> /dev/null

		IP_EXT=$(curl --max-time 3 ipecho.net/plain 2> /dev/null | egrep -ow '[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}' | head -n1 )
		[[ -z $IP_EXT ]] && IP_EXT="No connect"

	 export EDITOR='vim'
   #clear
   cat ~/dotfiles/banners/figlet.$(hostname -s) 2> /dev/null
   echo "$(hostname -s) - $IP_EXT"
 else
		# Settings when .zshrc executed locally
   export EDITOR='vim'
   source ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
 fi

# ZSH Autosuggest mapping
bindkey '  ' autosuggest-accept
bindkey '\e' autosuggest-execute
