---
# handlers file for dotfiles

# --------------------------------
# Send my vimrc && VUNDLE config
- name: Send (my)vimrc file
  copy:
    src: "{{ playbook_dir }}/../files/vimrc"
    dest: ~/.vimrc
  listen: send_vim_config

- name: Create ~/.vim directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.vim/bundle/
    - ~/.vim/colors/
  listen: send_vim_config

# TODO: Can Vundle install molokai?
- name: Send VIM colors file
  copy:
    src: "{{ playbook_dir }}/../files/molokai.vim"
    dest: ~/.vim/colors/
  listen: send_vim_config

- name: Install VUNDLE
  become: false
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
  listen: send_vim_config

- name: Clone VUNDLE plugins
  command: vim -E -s -c "source ~/.vimrc" +PluginInstall +qall -V
  ignore_errors: yes
  # failed_when: "'Cannot find' in vundle_plugins.stderr"
  listen: send_vim_config

# --------------------------------
# Send my ZSH config
- name: Send (my)zshrc file
  copy:
    src: "{{ playbook_dir }}/../files/zshrc"
    dest: ~/.zshrc
    backup: true
  listen: send_zsh_config

# Clone OHMYZSH
- name: Installing oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    update: true
  listen: send_zsh_config

- name: Clone OZSH plugins
  include_tasks: omzsh_plugins.yml
  listen: send_zsh_config

- name: Setting user shell to zsh
  # command: chsh -s /bin/zsh "{{ ansible_ssh_user }}"
  become: true
  user:
    name: "{{ ansible_ssh_user }}"
    shell: /bin/zsh
  listen: send_zsh_config

# - name: Update ohmzsh
#   command: git pull origin master
#   args:
#     chdir: ~/.oh-my-zsh
#   tags: test
